version: "3.9"

services:
  Prepmate-backend:
    container_name: Prepmate-backend
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    container_name: Prepmate-postgres 
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=Prepmate
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: